options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'

steps:
# Build the frontend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/terraform-429505/frontend:$COMMIT_SHA', './frontend']

# Push the frontend image to the Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/terraform-429505/frontend:$COMMIT_SHA']

# Build the backend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/terraform-429505/backend:$COMMIT_SHA', './backend']

# Push the backend image to the Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/terraform-429505/backend:$COMMIT_SHA']

images:
  - 'gcr.io/terraform-429505/frontend:latest'
  - 'gcr.io/terraform-429505/backend:latest'
